### ISSUE TITLE
Great stuff!

### ISSUE THREAD

**Issue by fondberg** [torrottum/ikea-ansluta-esphome#4]
I was just failing creating my own custom component with the same codebase.

A question:
Can you explain how I setup if I already know the AddressByteA and AddressByteB?

Is it as simple as 
```
(0xb8 << 4) + 0x66
==
3046
```
where 
0xb8 = A and 
0x66 = B
???

**Comment by fondberg** [comment]
I answer my own question here. Seems it sniffs the remote. Would be great to store this address persistently.

**Comment by fondberg** [comment]
Also found that I had to include all the header files in the yaml. Don't you need that?

**Comment by torrottum** [comment]
> I answer my own question here. Seems it sniffs the remote. Would be great to store this address persistently.

Yes, it sniffs for all remotes and publishes the state for them.
I think it's a bit over-kill for me though, since I only have one remote. So I don't mind changing it to only 
support one known address (and just log the address for the last sniffed remote, to have an easy way of finding the remote id for the setup process).

I'm considering switching approach though:
I have 4 lights paired with my remote. I currently have two problems:
1. Sometimes not all the lights turn on/off, that happens both using the remote and this. But it doesn't happen as often when using this.
1. The remote keeps its own state. If the lights are off and I click the remote 3 times the lights will go 50%, 100%, 50%. If I then turn off the lights with HA I need to press the remote 2 times to turn the lights on again. Because the remote sends off and then 50%. 

To solve this, I've been considering linking this directly to the lights (see #2), keep the state in MQTT and use the remote as a on/off button (ignoring the command from the remote and just flipping the state).

> Also found that I had to include all the header files in the yaml. Don't you need that?

Whoops, I think that's a mistake on my side. I probably had it in the yaml, but removed it and the header files are still inside `ikea_ansluta/src`.

**Comment by fondberg** [comment]
Thanks for the answer. Still struggling to get this to work though. Switched to a d1_mini and I either get an infinite loop after boot if I press the remote (2 times)  and the sniff command goes in (before an address is set) where it posts the state to mqtt or I get it to think it has address ffffffff if I publish new state from HA
```
[14:25:50][D][ansluta:053]: Topic: 'ikea_ansluta/light/ffffb866/set', Payload: 'ON'
[14:25:51][D][ansluta:073]: Publishing 'ON' to 'ikea_ansluta/light/ffffffff/s'
[14:25:51][D][ansluta:065]: Remote address: ffffffff
[14:26:08][D][ansluta:053]: Topic: 'ikea_ansluta/light/ffffb866/set', Payload: 'ON'
[14:26:08][D][ansluta:073]: Publishing 'ON' to 'ikea_ansluta/light/ffffffff/s'
[14:26:08][D][ansluta:065]: Remote address: ffffffff
```

It would be sweet if the address could be configurable in the yaml

**Comment by fondberg** [comment]
Also I see that it publishes to an "s" topic. Where as HA is configured to a /set topic.
```
[14:33:52][D][radio:066]: Sniffed command 02 from remote ffffb866
[14:33:52][D][ansluta:073]: Publishing 'ON' to 'ikea_ansluta/light/ffffb866/s'
```
Is this a bug I can fix?

Also there doesn't seem to be a state topic which HA can read from

**Comment by fondberg** [comment]
I got it to work by hardcoding my address 
```
    short address = 0xb866;
    // getRemoteAddressFromTopic(topic, address);
```
and changing 
```
    int len = topic_prefix.length() + 12;
```
to 
```
    int len = topic_prefix.length() + 16;
```

**Comment by fondberg** [comment]
I'm going to test a bit and propose a PR

**Comment by torrottum** [comment]
~Cool, I think it reads the address wrong from your remote. Would be interesting to see the packets that it sniffs. I've seen that other people gets a packet of 8 bytes, but I've only seen 6 myself.
Could you try running this branch: https://github.com/torrottum/ikea-ansluta-esphome/tree/issue-4-debug, press your remote a few times and post the log?~

**Comment by torrottum** [comment]
Or wait, I guess it's the conversion to/from hex :-)
0xb866 formatted using `%04x` is `ffffb866`, and I've only considered it being 4 chars long (my remote addr is 35c0).

**Comment by torrottum** [comment]
I've found the problem. It's bitshifting with signed chars (🤦 ).
```
char a = 0xb8;
char b = 0x66;
printf("%04x\n", ((unsigned char) a << 8) + (unsigned char) b);
// b866
printf("%04x\n", (a << 8) + b);
// ffffb866
```
I'll push a fix soon

**Comment by torrottum** [comment]
Pushed a fix to master now. You need to change the address in the topic in your HA config to `b866`

**Comment by fondberg** [comment]
Great! I'll test it

**Comment by torrottum** [comment]
Just want to give a heads up, I'm in the process of refactoring this to a proper custom component for esphome. Using the API instead of MQTT. It will also support 50% brightness: #7

Should make the setup a bit easier
